{-# OPTIONS -fno-warn-incomplete-patterns #-}
module Guic.Extjs.Printcodegen where

-- pretty-printer generated by the BNF converter

import Guic.Extjs.Abscodegen
import Char

-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString i)



instance Print WidgetType where
  prt i e = case e of
   Button  -> prPrec i 0 (concatD [doc (showString "Ext.Button")])


instance Print Parameter where
  prt i e = case e of
   Param object -> prPrec i 0 (concatD [prt 0 object])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Numb where
  prt i e = case e of
   NumbDouble n0 n -> prPrec i 0 (concatD [prt 0 n0 , doc (showString ".") , prt 0 n])
   NumbInteger n -> prPrec i 0 (concatD [prt 0 n])


instance Print DKey where
  prt i e = case e of
   DictKeyIdent id -> prPrec i 0 (concatD [prt 0 id])
   DictKeyString str -> prPrec i 0 (concatD [prt 0 str])


instance Print DValue where
  prt i e = case e of
   DictValue object -> prPrec i 0 (concatD [prt 0 object])


instance Print DItem where
  prt i e = case e of
   DictItem dkey dvalue -> prPrec i 0 (concatD [prt 0 dkey , doc (showString ":") , prt 0 dvalue])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Dictionary where
  prt i e = case e of
   Dict ditems -> prPrec i 0 (concatD [doc (showString "{") , prt 0 ditems , doc (showString "}")])


instance Print Array where
  prt i e = case e of
   Arr objects -> prPrec i 0 (concatD [doc (showString "[") , prt 0 objects , doc (showString "]")])


instance Print Object where
  prt i e = case e of
   ObjIdent id -> prPrec i 0 (concatD [prt 0 id])
   ObjString str -> prPrec i 0 (concatD [prt 0 str])
   ObjNumb num -> prPrec i 0 (concatD [prt 0 num])
   ObjDictionary dictionary -> prPrec i 0 (concatD [prt 0 dictionary])
   ObjArray array -> prPrec i 0 (concatD [prt 0 array])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print WidgetParams where
  prt i e = case e of
   WParams parameters dictionary -> prPrec i 0 (concatD [prt 0 parameters , doc (showString ",") , prt 0 dictionary])
   WNoParams dictionary -> prPrec i 0 (concatD [prt 0 dictionary])


instance Print Widget where
  prt i e = case e of
   NewWidget widgettype widgetparams -> prPrec i 0 (concatD [doc (showString "new") , prt 0 widgettype , doc (showString "(") , prt 0 widgetparams , doc (showString ")")])



